# Generated by Django 2.0.5 on 2018-05-17 21:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shokuhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('eat', models.CharField(max_length=255, null=True)),
                ('time_zone', models.CharField(max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='shokuhi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shockhi_check.User'),
        ),
    ]
