# Generated by Django 2.0.5 on 2018-05-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shockhi_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shokuhi',
            old_name='user_id',
            new_name='user',
        ),
    ]
