# Generated by Django 2.0.4 on 2018-05-10 14:22

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('shockhi_check', '0002_auto_20180507_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='token',
        ),
    ]
