# Generated by Django 2.0.4 on 2018-05-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shockhi_check', '0004_auto_20180511_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Token',
        ),
    ]
