# Generated by Django 2.0.4 on 2018-05-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shockhi_check', '0005_auto_20180512_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shokuhi',
            old_name='user',
            new_name='token',
        ),
    ]
